services:
  bot:
    build: .
    container_name: shuffle-feed
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./bot.db:/app/bot.db
      - ./logs:/app/logs
      - ./parser.session:/app/parser.session
      - ./downloads:/app/downloads
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    security_opt:
      - no-new-privileges:true